# Penalty weights mapped to master library findings
WEIGHTS = {
    # Critical Structural & Safety Hazards (50 points)
    "Bent tower member observed.": 50,
    "Missing tower member.": 50,
    "Tower foundation crack observed.": 50,
    "Generator fuel leakage observed.": 50,
    "Fuel tank leakage observed.": 50,
    "Fire risk observed around generator.": 50,
    "Battery swelling observed.": 50,
    "Battery leakage observed.": 50,
    "Battery string disconnected.": 50,
    "Grounding cable disconnected.": 50,
    "Water ingress observed inside cabinet.": 50,
    "Water leakage inside shelter.": 50,
    "Fire alarm not operational.": 50,
    "Equipment alarm active.": 50,
    "Transmission alarm active.": 50,

    # High Severity Defects (35–45 points)
    "Generator oil leakage observed.": 45,
    "Battery terminal corrosion observed.": 45,
    "Fire extinguisher missing.": 45,
    "Fire extinguisher expired.": 45,
    "Missing tower bolts.": 40,
    "Tower obstruction light not working.": 40,
    "Aviation light controller fault.": 40,
    "Coolant leakage observed.": 40,
    "Battery bank requires replacement.": 40,
    "Rectifier module fault detected.": 40,
    "Rectifier module missing.": 40,
    "Shelter air conditioner not operational.": 40,
    "High shelter temperature observed.": 40,
    "Grounding cable damaged.": 40,
    "Grounding bar corrosion observed.": 40,
    "Site security issue observed.": 40,
    "Tower foundation erosion observed.": 35,
    "Loose tower bolts.": 35,
    "Damaged climbing ladder.": 35,
    "RF jumper cable damaged.": 35,
    "Fuel tank corrosion observed.": 35,
    "AC breaker fault observed.": 35,
    "Open circuit breaker observed.": 35,
    "Cabinet lock missing.": 35,
    "Site gate not locked.": 35,
    "Microwave cable damaged.": 35,
    "ODU grounding not observed.": 35,

    # Medium Severity Defects (20–30 points)
    "Rust observed on tower members.": 30,
    "Corrosion observed on tower structure.": 30,
    "Damaged tower platform.": 30,
    "Damaged anti-climbing device.": 30,
    "Obstruction light cable damaged.": 30,
    "Antenna mounting loosened.": 30,
    "RRU mounting loosened.": 30,
    "Excessive generator vibration observed.": 30,
    "Abnormal generator noise detected.": 30,
    "Dry grass near generator.": 30,
    "Combustible materials near generator.": 30,
    "Battery cabinet not locked.": 30,
    "Battery voltage imbalance observed.": 30,
    "Battery capacity degradation observed.": 30,
    "Rectifier display not operational.": 30,
    "Earthing pit cover missing.": 30,
    "Cabinet door damaged.": 30,
    "Cabinet seal damaged.": 30,
    "Cabinet ventilation issue observed.": 30,
    "Roof leakage observed.": 30,
    "Wall damage observed.": 30,
    "Site fencing damaged.": 30,
    "Site gate damaged.": 30,
    "Cabinet temperature alarm active.": 30,
    "Tower climbing inspection not performed.": 30,
    "Cabin doors and power compartment not opened.": 30,
    "Feeder cables disorganized.": 25,
    "Feeder cables routed improperly.": 25,
    "Fiber cable protection missing.": 25,
    "Fiber cable routed outside tray.": 25,
    "Gas piping without cable trays.": 25,
    "Generator requires preventive maintenance.": 25,
    "Fuel piping routed improperly.": 25,
    "Generator grounding not observed.": 25,
    "Battery cabinet damaged.": 25,
    "Battery rack corrosion observed.": 25,
    "Commercial power cables disorganized.": 25,
    "DC cables disorganized.": 25,
    "Grounding connection loose.": 25,
    "Cables disorganized in cabinet.": 25,
    "Cables routed outside tray.": 25,
    "Unauthorized materials stored on site.": 25,
    "Microwave antenna requires inspection.": 25,
    "Dry grass near site assets.": 25,
    "Required image not provided.": 25,
    "Tower equipment image unclear.": 25,
    "Battery bank image not provided.": 25,
    "Power compartment image not provided.": 25,
    "Feeder cable support missing.": 20,
    "Feeder clamp missing.": 20,
    "Damaged antenna radome.": 20,
    "RRU protection cover damaged.": 20,
    "Weatherproofing not properly applied.": 20,
    "Weatherproofing deterioration observed.": 20,
    "Generator exhaust damaged.": 20,
    "Generator hour meter not operational.": 20,
    "Fuel level indicator defective.": 20,
    "AC breakers unlabeled.": 20,
    "DC cable labeling missing.": 20,
    "Earthing pit inaccessible.": 20,
    "Cabinet door not closing properly.": 20,
    "AC filter requires cleaning.": 20,
    "Equipment indicator alarm observed.": 20,
    "Waste materials present on site.": 20,
    "Abandoned cables require removal.": 20,
    "Image quality insufficient for verification.": 20,
    "Technician did not capture close-up image.": 20,
    "Cabinet internal view not provided.": 20,
    "Generator internal view not provided.": 20,

    # Low Severity / Housekeeping / Documentation (10–15 points)
    "Missing safety sign on tower.": 15,
    "Tower paint deterioration observed.": 15,
    "Missing anti-climbing device.": 15,
    "Missing aviation warning sign.": 15,
    "Fiber cable disorganized.": 15,
    "Unused feeder cables not removed.": 15,
    "Abandoned telecom cables require removal.": 15,
    "Antenna tilt label missing.": 15,
    "Antenna alignment requires verification.": 15,
    "Unused RF jumper not removed.": 15,
    "Fuel tank support damaged.": 15,
    "Fuel piping requires support.": 15,
    "Generator safety signage missing.": 15,
    "Battery corrosion observed.": 15,
    "Battery cabinet rust observed.": 15,
    "Battery cabinet ventilation blocked.": 15,
    "Rectifier configuration requires verification.": 15,
    "Missing breaker identification.": 15,
    "Unsecured DC cables observed.": 15,
    "DC breaker labeling missing.": 15,
    "DC termination requires maintenance.": 15,
    "Grounding identification missing.": 15,
    "Ground resistance measurement unavailable.": 15,
    "Cabinet corrosion observed.": 15,
    "Tray cover not closed properly.": 15,
    "PVC tray without cover.": 15,
    "Missing cable identification labels.": 15,
    "Floor damage observed.": 15,
    "Shelter ventilation inadequate.": 15,
    "Fire extinguisher inaccessible.": 15,
    "Fire safety sign missing.": 15,
    "Safety warning signs missing.": 15,
    "Equipment labeling missing.": 15,
    "Transmission cabinet disorganized.": 15,
    "Excess materials not removed.": 15,
    "Poor housekeeping observed.": 15,
    "Site cleaning required.": 15,
    "Image does not represent required item.": 15,
    "Image position incorrect.": 15,
    "Equipment identification unclear.": 15,
    "Generator area housekeeping poor.": 10,
    "Battery cabinet cleanliness poor.": 10,
    "Commercial power box housekeeping poor.": 10,
    "Cabinet housekeeping poor.": 10,
    "Unused cables not removed.": 10,
    "Shelter cleanliness poor.": 10,
    "Equipment cleanliness poor.": 10,

    # Positive Findings (0 Penalty Points)
    "No issue observed.": 0,
    "Tower condition satisfactory.": 0,
    "Generator condition satisfactory.": 0,
    "Battery system condition satisfactory.": 0,
    "Power system condition satisfactory.": 0,
    "Grounding system condition satisfactory.": 0,
    "Cabinet condition satisfactory.": 0,
    "Shelter condition satisfactory.": 0,
    "Fire protection equipment satisfactory.": 0,
    "Housekeeping condition satisfactory.": 0,
    "Site complies with audit requirements.": 0
}

def calculate_audit_score(findings):
    total_penalty = sum(WEIGHTS.get(item, 10) for item in findings)
    
    # Calculate health index score (100 is perfect)
    health_score = max(0, 100 - total_penalty)
    
    if total_penalty >= 70:
        priority = "CRITICAL"
    elif total_penalty >= 30:
        priority = "HIGH"
    elif total_penalty > 0:
        priority = "MEDIUM"
    else:
        priority = "COMPLIANT"
        
    return {
        "penalty_points": total_penalty,
        "health_score": health_score,
        "priority": priority
    }
